 

Moves(1).UNAME = "RAMPAGE"
Moves(1).DESCRIPTION = "FLIPS A COIN. IF HEADS, REMOVES A FOE BOOSTER"
Moves(1).POWER = 2
Moves(1).STATUS = 0
Moves(1).CFCHECK = 0
Moves(1).CFSECONDARY = 1
Moves(1).BOOSTERSCALE = 0

Moves(2).UNAME = "RAMPAGE"
Moves(2).DESCRIPTION = "IF HEADS, KICKS THE FOE TO THE BENCH"
Moves(2).POWER = 3
Moves(2).STATUS = 0
Moves(2).CFCHECK = 0
Moves(2).CFSECONDARY = 1
Moves(2).BOOSTERSCALE = 0

Moves(3).UNAME = "BEAVER NUKE"
Moves(3).DESCRIPTION = "IF TAILS, BOMBR RECEIVES 2HP OF RECOIL"
Moves(3).POWER = 4
Moves(3).STATUS = 0
Moves(3).CFCHECK = 0
Moves(3).CFSECONDARY = 1
Moves(3).BOOSTERSCALE = 0

Moves(4).UNAME = "BEAVER NUKE"
Moves(4).DESCRIPTION = "RECOIL REDUCED TO 1HP"
Moves(4).POWER = 5
Moves(4).STATUS = 0
Moves(4).CFCHECK = 0
Moves(4).CFSECONDARY = 1
Moves(4).BOOSTERSCALE = 0

Moves(5).UNAME = "ASSAULT CROW"
Moves(5).DESCRIPTION = "FLIPS 3 COINS, EACH TAILS DAMAGES"
Moves(5).POWER = 2
Moves(5).STATUS = 0
Moves(5).CFCHECK = 0
Moves(5).CFSECONDARY = 0
Moves(5).BOOSTERSCALE = 0

Moves(6).UNAME = "ASSAULT CROW"
Moves(6).DESCRIPTION = "EACH BOOSTER ADDS ONE MORE COIN"
Moves(6).POWER = 2
Moves(6).STATUS = 0
Moves(6).CFCHECK = 0
Moves(6).CFSECONDARY = 0
Moves(6).BOOSTERSCALE = 0

Moves(7).UNAME = "SPIKY SHIELD"
Moves(7).DESCRIPTION = "REDUCES INCOMING DAMAGE 1HP"
Moves(7).POWER = 0
Moves(7).STATUS = 5
Moves(7).CFCHECK = 0
Moves(7).CFSECONDARY = 0
Moves(7).BOOSTERSCALE = 0

Moves(8).UNAME = "SPIKY SHIELD"
Moves(8).DESCRIPTION = "EACH BOOSTER REDUCES DAMAGE ANOTHER 2HP"
Moves(8).POWER = 0
Moves(8).STATUS = 5
Moves(8).CFCHECK = 0
Moves(8).CFSECONDARY = 0
Moves(8).BOOSTERSCALE = 0

Moves(9).UNAME = "ZAPPER"
Moves(9).DESCRIPTION = "PARALYZES IF HEADS, FAILS IF TAILS"
Moves(9).POWER = 2
Moves(9).STATUS = 1
Moves(9).CFCHECK = 1
Moves(9).CFSECONDARY = 0
Moves(9).BOOSTERSCALE = 0

Moves(10).UNAME = "ZAPPER"
Moves(10).DESCRIPTION = "EACH BOOSTER ADDS 2HP OF DAMAGE"
Moves(10).POWER = 2
Moves(10).STATUS = 1
Moves(10).CFCHECK = 1
Moves(10).CFSECONDARY = 0
Moves(10).BOOSTERSCALE = 2

Moves(11).UNAME = "INFILTRATE"
Moves(11).DESCRIPTION = "DAMAGES A RANDOM BENCHED FOE"
Moves(11).POWER = 3
Moves(11).STATUS = 0
Moves(11).CFCHECK = 0
Moves(11).CFSECONDARY = 0
Moves(11).BOOSTERSCALE = 0

Moves(12).UNAME = "INFILTRATE"
Moves(12).DESCRIPTION = "PEEKS FOE BENCH AND DAMAGES CHOSEN FOE"
Moves(12).POWER = 4
Moves(12).STATUS = 0
Moves(12).CFCHECK = 0
Moves(12).CFSECONDARY = 0
Moves(12).BOOSTERSCALE = 0

Moves(13).UNAME = "CRANE PULL"
Moves(13).DESCRIPTION = "DRAWS TWO CARDS"
Moves(13).POWER = 0
Moves(13).STATUS = 0
Moves(13).CFCHECK = 0
Moves(13).CFSECONDARY = 0
Moves(13).BOOSTERSCALE = 0

Moves(14).UNAME = "CRANE PULL"
Moves(14).DESCRIPTION = "DRAWS 2 CARDS AND A RANDOM FOE. DAMAGES HIM"
Moves(14).POWER = 3
Moves(14).STATUS = 0
Moves(14).CFCHECK = 0
Moves(14).CFSECONDARY = 0
Moves(14).BOOSTERSCALE = 0

Moves(15).UNAME = "SCORCHING FIRE"
Moves(15).DESCRIPTION = "IF HEADS, THE FOE IS BURNED"
Moves(15).POWER = 3
Moves(15).STATUS = 2
Moves(15).CFCHECK = 0
Moves(15).CFSECONDARY = 1
Moves(15).BOOSTERSCALE = 0

Moves(16).UNAME = "SCORCHING FIRE"
Moves(16).DESCRIPTION = "THE BURN EFFECT IS GUARANTEED"
Moves(16).POWER = 4
Moves(16).STATUS = 2
Moves(16).CFCHECK = 0
Moves(16).CFSECONDARY = 0
Moves(16).BOOSTERSCALE = 0

