 

Moves(1).UNAME = "SHAKEDOWN"
Moves(1).DESCRIPTION = "FLIPS A COIN. IF HEADS, REMOVES A FOE BOOSTER"
Moves(1).POWER = 2
Moves(1).STATUS = 0
Moves(1).CFCHECK = 0
Moves(1).CFSECONDARY = 1
Moves(1).BOOSTERSCALE = 0

Moves(2).UNAME = "SMACKDOWN"
Moves(2).DESCRIPTION = "IF HEADS, KICKS THE FOE TO THE BENCH"
Moves(2).POWER = 3
Moves(2).STATUS = 0
Moves(2).CFCHECK = 0
Moves(2).CFSECONDARY = 1
Moves(2).BOOSTERSCALE = 0

Moves(3).UNAME = "BEAVER BOMB"
Moves(3).DESCRIPTION = "IF TAILS, BOMBR RECEIVES 2HP OF RECOIL"
Moves(3).POWER = 4
Moves(3).STATUS = 0
Moves(3).CFCHECK = 0
Moves(3).CFSECONDARY = 1
Moves(3).BOOSTERSCALE = 0

Moves(4).UNAME = "BEAVER NUKE"
Moves(4).DESCRIPTION = "RECOIL REDUCED TO 1HP"
Moves(4).POWER = 5
Moves(4).STATUS = 0
Moves(4).CFCHECK = 0
Moves(4).CFSECONDARY = 1
Moves(4).BOOSTERSCALE = 0

Moves(5).UNAME = "ASSAULT CROW"
Moves(5).DESCRIPTION = "FLIPS 3 COINS, EACH TAILS DAMAGES"
Moves(5).POWER = 2
Moves(5).STATUS = 0
Moves(5).CFCHECK = 0
Moves(5).CFSECONDARY = 0
Moves(5).BOOSTERSCALE = 0

Moves(6).UNAME = "MINIGUN CROW"
Moves(6).DESCRIPTION = "EACH BOOSTER ADDS ONE MORE COIN"
Moves(6).POWER = 2
Moves(6).STATUS = 0
Moves(6).CFCHECK = 0
Moves(6).CFSECONDARY = 0
Moves(6).BOOSTERSCALE = 0

Moves(7).UNAME = "SPIKY SHIELD"
Moves(7).DESCRIPTION = "REDUCES INCOMING DAMAGE 1HP"
Moves(7).POWER = 0
Moves(7).STATUS = 5
Moves(7).CFCHECK = 0
Moves(7).CFSECONDARY = 0
Moves(7).BOOSTERSCALE = 0

Moves(8).UNAME = "MINE SHIELD"
Moves(8).DESCRIPTION = "EACH BOOSTER REDUCES DAMAGE ANOTHER 2HP"
Moves(8).POWER = 0
Moves(8).STATUS = 5
Moves(8).CFCHECK = 0
Moves(8).CFSECONDARY = 0
Moves(8).BOOSTERSCALE = 0

Moves(9).UNAME = "ZAPPER"
Moves(9).DESCRIPTION = "PARALYZES IF HEADS, FAILS IF TAILS"
Moves(9).POWER = 2
Moves(9).STATUS = 1
Moves(9).CFCHECK = 1
Moves(9).CFSECONDARY = 0
Moves(9).BOOSTERSCALE = 0

Moves(10).UNAME = "GAMMA ZAPPER"
Moves(10).DESCRIPTION = "EACH BOOSTER ADDS 2HP OF DAMAGE"
Moves(10).POWER = 2
Moves(10).STATUS = 1
Moves(10).CFCHECK = 1
Moves(10).CFSECONDARY = 0
Moves(10).BOOSTERSCALE = 2

Moves(11).UNAME = "INFILTRATE"
Moves(11).DESCRIPTION = "DAMAGES A RANDOM BENCHED FOE"
Moves(11).POWER = 3
Moves(11).STATUS = 0
Moves(11).CFCHECK = 0
Moves(11).CFSECONDARY = 0
Moves(11).BOOSTERSCALE = 0

Moves(12).UNAME = "ESPIONAGE"
Moves(12).DESCRIPTION = "PEEKS FOE BENCH AND DAMAGES CHOSEN FOE"
Moves(12).POWER = 4
Moves(12).STATUS = 0
Moves(12).CFCHECK = 0
Moves(12).CFSECONDARY = 0
Moves(12).BOOSTERSCALE = 0

Moves(13).UNAME = "CRANE PULL"
Moves(13).DESCRIPTION = "DRAWS TWO CARDS"
Moves(13).POWER = 0
Moves(13).STATUS = 0
Moves(13).CFCHECK = 0
Moves(13).CFSECONDARY = 0
Moves(13).BOOSTERSCALE = 0

Moves(14).UNAME = "CRANE GACHA"
Moves(14).DESCRIPTION = "DRAWS 2 CARDS AND A RANDOM FOE. DAMAGES HIM"
Moves(14).POWER = 3
Moves(14).STATUS = 0
Moves(14).CFCHECK = 0
Moves(14).CFSECONDARY = 0
Moves(14).BOOSTERSCALE = 0

Moves(15).UNAME = "SCORCHING FIRE"
Moves(15).DESCRIPTION = "IF HEADS, THE FOE IS BURNED"
Moves(15).POWER = 3
Moves(15).STATUS = 2
Moves(15).CFCHECK = 0
Moves(15).CFSECONDARY = 1
Moves(15).BOOSTERSCALE = 0

Moves(16).UNAME = "SCORCHING NAPALM"
Moves(16).DESCRIPTION = "THE BURN EFFECT IS GUARANTEED"
Moves(16).POWER = 4
Moves(16).STATUS = 2
Moves(16).CFCHECK = 0
Moves(16).CFSECONDARY = 0
Moves(16).BOOSTERSCALE = 0

Moves(17).UNAME = "GAS CLOUD"
Moves(17).DESCRIPTION = "THE FOE IS POISONED"
Moves(17).POWER = 2
Moves(17).STATUS = 3
Moves(17).CFCHECK = 0
Moves(17).CFSECONDARY = 0
Moves(17).BOOSTERSCALE = 0

Moves(18).UNAME = "GAS NOVA"
Moves(18).DESCRIPTION = "DOUBLE DAMAGE IF FOE IS POISONED"
Moves(18).POWER = 3
Moves(18).STATUS = 0
Moves(18).CFCHECK = 0
Moves(18).CFSECONDARY = 0
Moves(18).BOOSTERSCALE = 0

Moves(19).UNAME = "BLOB TRAP"
Moves(19).DESCRIPTION = "IF HEADS, THE FOE IS STUNNED A TURN"
Moves(19).POWER = 0
Moves(19).STATUS = 4
Moves(19).CFCHECK = 1
Moves(19).CFSECONDARY = 0
Moves(19).BOOSTERSCALE = 0

Moves(20).UNAME = "BLOB CANNON"
Moves(20).DESCRIPTION = "DEALS 1/3 OF GOOSTAV CURRENT HP"
Moves(20).POWER = 0
Moves(20).STATUS = 0
Moves(20).CFCHECK = 0
Moves(20).CFSECONDARY = 0
Moves(20).BOOSTERSCALE = 0

Moves(21).UNAME = "TRIPLE VIRAL"
Moves(21).DESCRIPTION = "MAY POISON, PARALYZE OR CONFUSE"
Moves(21).POWER = 2
Moves(21).STATUS = 0
Moves(21).CFCHECK = 0
Moves(21).CFSECONDARY = 0
Moves(21).BOOSTERSCALE = 0

Moves(22).UNAME = "TRIPLE TOXIN"
Moves(22).DESCRIPTION = "PROVOKES CONFUSION AND POISON SIMULTANEOUSLY"
Moves(22).POWER = 2
Moves(22).STATUS = 6
Moves(22).CFCHECK = 0
Moves(22).CFSECONDARY = 0
Moves(22).BOOSTERSCALE = 0

Moves(23).UNAME = "SINE WAVE"
Moves(23).DESCRIPTION = "EVERY TURN DEALS EXTRA 2HP"
Moves(23).POWER = 2
Moves(23).STATUS = 0
Moves(23).CFCHECK = 0
Moves(23).CFSECONDARY = 0
Moves(23).BOOSTERSCALE = 0

Moves(24).UNAME = "COSINE WAVE"
Moves(24).DESCRIPTION = "EVERY TURN DEALS 1HP LESS"
Moves(24).POWER = 6
Moves(24).STATUS = 0
Moves(24).CFCHECK = 0
Moves(24).CFSECONDARY = 0
Moves(24).BOOSTERSCALE = 0

Moves(25).UNAME = "SCREECH SONG"
Moves(25).DESCRIPTION = "IF HEADS, CONFUSES"
Moves(25).POWER = 2
Moves(25).STATUS = 7
Moves(25).CFCHECK = 0
Moves(25).CFSECONDARY = 1
Moves(25).BOOSTERSCALE = 0

Moves(26).UNAME = "SCREECH HYMN"
Moves(26).DESCRIPTION = "GUARANTEED CONFUSION"
Moves(26).POWER = 2
Moves(26).STATUS = 7
Moves(26).CFCHECK = 0
Moves(26).CFSECONDARY = 0
Moves(26).BOOSTERSCALE = 0

Moves(27).UNAME = "BEACON SIGNAL"
Moves(27).DESCRIPTION = "HEALS 1HP, IF HEADS, INVOKES A MONSTER"
Moves(27).POWER = 0
Moves(27).STATUS = 0
Moves(27).CFCHECK = 0
Moves(27).CFSECONDARY = 1
Moves(27).BOOSTERSCALE = 0

Moves(28).UNAME = "BEACON CALL"
Moves(28).DESCRIPTION = "SWITCHES WITH AN ALLY. HEALS 30HP PER BOOSTER"
Moves(28).POWER = 0
Moves(28).STATUS = 0
Moves(28).CFCHECK = 0
Moves(28).CFSECONDARY = 0
Moves(28).BOOSTERSCALE = 0

Moves(29).UNAME = "BLOOM"
Moves(29).DESCRIPTION = "HEALS BACK HALF OF THE DAMAGE DEALT"
Moves(29).POWER = 2
Moves(29).STATUS = 0
Moves(29).CFCHECK = 0
Moves(29).CFSECONDARY = 0
Moves(29).BOOSTERSCALE = 0

Moves(30).UNAME = "BLOSSOM"
Moves(30).DESCRIPTION = "HEALS AN ALLY ALL THE DAMAGE DEALT"
Moves(30).POWER = 2
Moves(30).STATUS = 0
Moves(30).CFCHECK = 0
Moves(30).CFSECONDARY = 0
Moves(30).BOOSTERSCALE = 0

Moves(31).UNAME = "VODKA GULP"
Moves(31).DESCRIPTION = "CAUSES SELF CONFUSION BUT HEALS 30HP"
Moves(31).POWER = 0
Moves(31).STATUS = 8
Moves(31).CFCHECK = 0
Moves(31).CFSECONDARY = 0
Moves(31).BOOSTERSCALE = 0

Moves(32).UNAME = "VODKA SPITE"
Moves(32).DESCRIPTION = "IF CONFUSED, HEALS IT AND CONFUSE FOE"
Moves(32).POWER = 4
Moves(32).STATUS = 7
Moves(32).CFCHECK = 0
Moves(32).CFSECONDARY = 0
Moves(32).BOOSTERSCALE = 0

'Moves that come with equipable objects'


Moves(33).UNAME = "PRIMAL RAGE"
Moves(33).DESCRIPTION = "IF HEADS, DEALS DOUBLE DAMAGE IF 1/2 HP"
Moves(33).POWER = 3
Moves(33).STATUS = 0
Moves(33).CFCHECK = 0
Moves(33).CFSECONDARY = 1
Moves(33).BOOSTERSCALE = 0

Moves(34).UNAME = "HIBERNATE"
Moves(34).DESCRIPTION = "HEALS 4HP, BUT SLEEPS THE NEXT TURN"
Moves(34).POWER = 0
Moves(34).STATUS = 0
Moves(34).CFCHECK = 0
Moves(34).CFSECONDARY = 0
Moves(34).BOOSTERSCALE = 0

Moves(35).UNAME = "DOWNLOAD"
Moves(35).DESCRIPTION = "GAIN ONE OR THREE BOOSTERS ON COINFLIP"
Moves(35).POWER = 0
Moves(35).STATUS = 0
Moves(35).CFCHECK = 1
Moves(35).CFSECONDARY = 0
Moves(35).BOOSTERSCALE = 0

Moves(36).UNAME = "ELECTROCUTE"
Moves(36).DESCRIPTION = "THE USER LOSES 1 OR 2HP ON COINFLIP"
Moves(36).POWER = 4
Moves(36).STATUS = 8
Moves(36).CFCHECK = 0
Moves(36).CFSECONDARY = 1
Moves(36).BOOSTERSCALE = 0

Moves(37).UNAME = "PARASYTE"
Moves(37).DESCRIPTION = "1HP IS DRAINED PER TURN FROM FOE"
Moves(37).POWER = 0
Moves(37).STATUS = 10
Moves(37).CFCHECK = 0
Moves(37).CFSECONDARY = 0
Moves(37).BOOSTERSCALE = 0

Moves(38).UNAME = "CORRODER"
Moves(38).DESCRIPTION = "ROBOT FOES RECEIVE DOUBLE DAMAGE"
Moves(38).POWER = 3
Moves(38).STATUS = 0
Moves(38).CFCHECK = 0
Moves(38).CFSECONDARY = 0
Moves(38).BOOSTERSCALE = 0

Moves(39).UNAME = "AMPLIFIED WAVE"
Moves(39).DESCRIPTION = "DEALS EXTRA HP PER BOOSTER BUT KEEPS THEM"
Moves(39).POWER = 2
Moves(39).STATUS = 0
Moves(39).CFCHECK = 0
Moves(39).CFSECONDARY = 0
Moves(39).BOOSTERSCALE = 1

Moves(40).UNAME = "MODULO"
Moves(40).DESCRIPTION = "DEALS A THIRD OF THE FOE HP"
Moves(40).POWER = 0
Moves(40).STATUS = 0
Moves(40).CFCHECK = 0
Moves(40).CFSECONDARY = 0
Moves(40).BOOSTERSCALE = 0


Moves(32).UNAME = "MYTHIC SWORD"
Moves(32).DESCRIPTION = "THREE COINS. EACH COINS REDUCES DAMAGE"
Moves(32).POWER = 5
Moves(32).STATUS = 0
Moves(32).CFCHECK = 0
Moves(32).CFSECONDARY = 0
Moves(32).BOOSTERSCALE = 0




